# Generated by Django 5.2.17 on 2026-08-16 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_usersecret'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSecret',
        ),
    ]
